### ISSUE TITLE
Trouble exporting pdf/pptx

### ISSUE THREAD

**Issue by elputnam** [marp-team/marp-vscode#284]
Hello,

I am trying to export a marp slide deck from VSCode. I have no trouble exporting html, but when I try to export as pdf or pptx, the action doesn't complete. Everything seems up-to-date for both extension and VSCode.

**Comment by yhatt** [comment]
Did you read the error message that is shown when you've act for exporting? The extension should have outputted a helpful message:

![error](https://user-images.githubusercontent.com/3993388/131930686-009ffdf7-c11b-4417-898e-0c811659a823.png)

**Comment by elputnam** [comment]
No error message comes up. It just runs indefinitely (even after 20 minutes) until I close VScode.

**Comment by elputnam** [comment]
This error came up when I checked runtime status.
![Screenshot 2021-09-03 095614](https://user-images.githubusercontent.com/63127590/131979092-94b4d577-3d89-4f4f-97d9-438d4a1dda28.png)

**Comment by yhatt** [comment]
May be related to https://github.com/puppeteer/puppeteer/issues/4609: You may be using too old Chromium/Chrome (76 and older). Please check the version of installed Chromium/Chrome and upgrade to the latest version (92).

If still not fixed, please share more details:

- Which OS you are using?
- Are there other extensions that are using together with Marp?
- Where is a Markdown that you have tried to export located in? (e.g. Local workspace, Remote container such as WSL/SSH/Docker/Live share)
- After acted the export command, What were outputted in a "Console" tab on the developer tool? (Help -> "Toggle Developer Tools" -> "Console" tab)

**Comment by elputnam** [comment]
My Chrome seems to be up-to-date:
<img width="513" alt="Screenshot 2021-09-03 120345" src="https://user-images.githubusercontent.com/63127590/131996035-b01e7e75-310b-40e1-9217-19577f3223e1.png">

I am using Windows Version 10.0.19042.

I am using Markdown linit in addition to the Marp extension. I deactivated it but it did not resolve the issue. 

The markdown is located on my local workspace and I am trying to export to the same folder.

Here is what was output in the Console Tab:

<img width="348" alt="Screenshot 2021-09-03 121423" src="https://user-images.githubusercontent.com/63127590/131997191-8be757b9-ace7-4130-8e32-eaa5c95d47cb.png">

mainThreadExtensionService.ts:63 [[object Object]]Protocol error (IO.read): Invalid parameters handle: string value expected

Error: Protocol error (IO.read): Invalid parameters handle: string value expected
	at c:\Users\0123213s\.vscode\extensions\marp-team.marp-vscode-1.3.0\node_modules\puppeteer-core\lib\cjs\puppeteer\common\Connection.js:217:63
	at new Promise (<anonymous>)
	at CDPSession.send (c:\Users\0123213s\.vscode\extensions\marp-team.marp-vscode-1.3.0\node_modules\puppeteer-core\lib\cjs\puppeteer\common\Connection.js:216:16)
	at Readable.read [as _read] (c:\Users\0123213s\.vscode\extensions\marp-team.marp-vscode-1.3.0\node_modules\puppeteer-core\lib\cjs\puppeteer\common\helper.js:276:43)
	at Readable.read (internal/streams/readable.js:481:10)
	at createAsyncIterator (internal/streams/readable.js:1136:54)
	at createAsyncIterator.next (<anonymous>)
	at Object.getReadableAsBuffer (c:\Users\0123213s\.vscode\extensions\marp-team.marp-vscode-1.3.0\node_modules\puppeteer-core\lib\cjs\puppeteer\common\helper.js:247:22)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async Page.pdf (c:\Users\0123213s\.vscode\extensions\marp-team.marp-vscode-1.3.0\node_modules\puppeteer-core\lib\cjs\puppeteer\common\Page.js:1997:16)
	at async c:\Users\0123213s\.vscode\extensions\marp-team.marp-vscode-1.3.0\node_modules\@marp-team\marp-cli\lib\marp-cli-414cc758.js:44:49525
	at async Sl.usePuppeteer (c:\Users\0123213s\.vscode\extensions\marp-team.marp-vscode-1.3.0\node_modules\@marp-team\marp-cli\lib\marp-cli-414cc758.js:44:53293)
	at async Sl.convertFileToPDF (c:\Users\0123213s\.vscode\extensions\marp-team.marp-vscode-1.3.0\node_modules\@marp-team\marp-cli\lib\marp-cli-414cc758.js:44:49421)
	at async Sl.convertFile (c:\Users\0123213s\.vscode\extensions\marp-team.marp-vscode-1.3.0\node_modules\@marp-team\marp-cli\lib\marp-cli-414cc758.js:44:48333)
	at async Sl.convertFiles (c:\Users\0123213s\.vscode\extensions\marp-team.marp-vscode-1.3.0\node_modules\@marp-team\marp-cli\lib\marp-cli-414cc758.js:44:49116)
	at async fp (c:\Users\0123213s\.vscode\extensions\marp-team.marp-vscode-1.3.0\node_modules\@marp-team\marp-cli\lib\marp-cli-414cc758.js:44:83786)
$onExtensionRuntimeError @ mainThreadExtensionService.ts:64
_doInvokeHandler @ rpcProtocol.ts:472
_invokeHandler @ rpcProtocol.ts:457
_receiveRequest @ rpcProtocol.ts:373
_receiveOneMessage @ rpcProtocol.ts:295
(anonymous) @ rpcProtocol.ts:160
fire @ event.ts:577
fire @ ipc.net.ts:513
_receiveMessage @ ipc.net.ts:871
(anonymous) @ ipc.net.ts:710
fire @ event.ts:577
acceptChunk @ ipc.net.ts:286
(anonymous) @ ipc.net.ts:247
k @ ipc.net.ts:50
emit @ events.js:315
addChunk @ internal/streams/readable.js:309
readableAddChunk @ internal/streams/readable.js:284
Readable.push @ internal/streams/readable.js:223
onStreamRead @ internal/stream_base_commons.js:188

**Comment by yhatt** [comment]
Don't you have installed Google Chrome Canary? If so, please check its version too. [Chrome launcher that is used by Marp is prefer a canary build than the stable release](https://github.com/GoogleChrome/chrome-launcher/blob/12b2c8e3773036d18a4b6938fc1a759a8c7b98e5/src/chrome-finder.ts#L188-L189).

If that does not work, try setting the path to the stable Chrome executable in the extension setting: `Markdown > Marp: Chrome Path`.

![](https://user-images.githubusercontent.com/3993388/59206175-5ca81d00-8bdf-11e9-92ff-5b82e4af3152.png)

**Comment by elputnam** [comment]
I installed Chrome Canary and it now works. Thank you!
