### ISSUE TITLE
v0.3.0 does not activate extension by "Cannot find module 'os-tmpdir'"

### ISSUE THREAD

**Issue by yhatt** [marp-team/marp-vscode#34]

**Comment by yhatt** [comment]
Hotfix release v0.3.1 has shipped. It should not be required added dependencies. We will research this issue.

### Stacktrace

```
Error: Cannot find module 'os-tmpdir'
	at Function.Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
	at Function.Module._load (internal/modules/cjs/loader.js:528:25)
	at Function.t._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:729:537)
	at Function.t.getExtensionPathIndex.then.a._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:691:639)
	at Function.t.getExtensionPathIndex.then.r._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:655:197)
	at Module.require (internal/modules/cjs/loader.js:658:17)
	at n (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:15:874)
	at Object.<anonymous> (/Users/yhatt/.vscode/extensions/marp-team.marp-vscode-0.3.0/node_modules/tmp/lib/tmp.js:16:12)
	at Object.<anonymous> (/Users/yhatt/.vscode/extensions/marp-team.marp-vscode-0.3.0/node_modules/tmp/lib/tmp.js:463:3)
	at Module.t._initNodeRequire.r._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:16:90)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
	at Module.load (internal/modules/cjs/loader.js:620:32)
	at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
	at Function.Module._load (internal/modules/cjs/loader.js:551:3)
	at Function.t._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:729:537)
	at Function.t.getExtensionPathIndex.then.a._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:691:639)
	at Function.t.getExtensionPathIndex.then.r._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:655:197)
	at Module.require (internal/modules/cjs/loader.js:658:17)
	at n (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:15:874)
	at Object.<anonymous> (/Users/yhatt/.vscode/extensions/marp-team.marp-vscode-0.3.0/node_modules/@marp-team/marp-cli/lib/marp-cli.js:1:960)
	at Object.<anonymous> (/Users/yhatt/.vscode/extensions/marp-team.marp-vscode-0.3.0/node_modules/@marp-team/marp-cli/lib/marp-cli.js:3:3)
	at Module.t._initNodeRequire.r._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:16:90)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
	at Module.load (internal/modules/cjs/loader.js:620:32)
	at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
	at Function.Module._load (internal/modules/cjs/loader.js:551:3)
	at Function.t._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:729:537)
	at Function.t.getExtensionPathIndex.then.a._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:691:639)
	at Function.t.getExtensionPathIndex.then.r._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:655:197)
	at Module.require (internal/modules/cjs/loader.js:658:17)
	at n (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:15:874)
	at Object.<anonymous> (/Users/yhatt/.vscode/extensions/marp-team.marp-vscode-0.3.0/lib/extension.js:1:440)
	at Object.<anonymous> (/Users/yhatt/.vscode/extensions/marp-team.marp-vscode-0.3.0/lib/extension.js:3:3)
	at Module.t._initNodeRequire.r._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:16:90)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
	at Module.load (internal/modules/cjs/loader.js:620:32)
	at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
	at Function.Module._load (internal/modules/cjs/loader.js:551:3)
	at Function.t._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:729:537)
	at Function.t.getExtensionPathIndex.then.a._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:691:639)
	at Function.t.getExtensionPathIndex.then.r._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:655:197)
	at Module.require (internal/modules/cjs/loader.js:658:17)
	at require (internal/modules/cjs/helpers.js:20:18)
	at Function.i [as __$__nodeRequire] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:31:542)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:717:918
	at E._doActivateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:718:2)
	at E._activateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:716:772)
	at E.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:714:224)
	at Generator.next (<anonymous>)
	at n (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:11:176)
	at new Promise (<anonymous>)
	at n (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:10:975)
	at Object.actualActivateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:713:946)
	at p._activateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:457:765)
	at define._activateExtensions.i.length.Promise.all.o.map.e (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:457:449)
	at Array.map (<anonymous>)
	at p._activateExtensions (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:457:437)
	at p.activateById (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:455:604)
	at E._activateById (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:715:497)
	at E.activateByIdWithErrors (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:715:555)
	at se.activate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:710:676)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/markdown-language-features/dist/extension.js:1:873024
	at e.fromExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/markdown-language-features/dist/extension.js:1:873124)
	at Array.map (<anonymous>)
	at _.getCurrentContributions (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/markdown-language-features/dist/extension.js:1:873766)
	at _.get contributions [as contributions] (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/markdown-language-features/dist/extension.js:1:873669)
	at Function.revive (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/markdown-language-features/dist/extension.js:1:69364)
	at l.deserializeWebviewPanel (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/markdown-language-features/dist/extension.js:1:65872)
	at l.$deserializeWebviewPanel (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:582:844)
	at d._doInvokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:622:11)
	at d._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:621:716)
	at d._receiveRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:620:394)
	at d._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:619:141)
	at define.constructor._protocol.onMessage.e (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:617:400)
	at u.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:44:708)
	at e (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:40:460)
	at u.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:44:708)
	at a (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:172:467)
	at e (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:172:513)
	at u.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:44:708)
	at y._receiveMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:181:276)
	at define.constructor._socketDisposables.push._socketReader.onMessage.e (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:178:415)
	at u.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:44:708)
	at f.acceptChunk (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:175:35)
	at define.constructor._register._socket.onData.e (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:174:410)
	at Socket.t (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:182:689)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:279:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onread (net.js:636:20)
```

**Comment by yhatt** [comment]
`vsce package --yarn` seems to use vsce's `tmp` module (v0.0.29: requires `os-tmpdir`) instead of our dependency (`v0.1.0`).

**Comment by yhatt** [comment]
It seems to bring from the behavior of package manager rather than vsce's packaging process. See #35.
